version: '3'
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - 1521:1521
      - 8080:8080
    environment:
      - ORACLE_ALLOW_REMOTE=true
    volumes:
      - oracle_semana_5:/opt/oracle/oradata

volumes:
  oracle_semana_5: