version: '3'
services:
  front:
    image: frontend
    ports:
      - 8080:80
    container_name: front
    # Outras configurações adicionais, se necessário

  banco_de_dados:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    container_name: banco_de_dados
    # Outras configurações adicionais, se necessário

volumes:
  db_data:
